version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - ma:/mariadb
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - wp:/var/www/aamhamdi/html/
    depends_on:
      - mariadb
    env_file:
      - .env
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - wp:/var/www/aamhamdi/html
    depends_on:
      - wordpress
volumes:
  wp :
    driver : local
  ma :
    driver : local

